language: generic
os: linux
dist: bionic

jobs:
  include:
    - os: linux
      env:
        - HOST="generic"
    - os: linux
      env:
        - HOST="x86_64"
    - os: linux
      env:
        - HOST="i686"

script:
  ci/build.sh ${HOST}

install:
  ci/install.sh



before_deploy:
  - git config --local user.name "Antonino Natale"
  - git config --local user.email "antonio.natale97@hotmail.com"
  - export TRAVIS_TAG=v0.6.$(date +'%Y%m%d')
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  token:
    secure: "XNF+7VZVkJ+PkJjR8OZg0VYSLStINThb8nh678/DLBfPH3BKZxFLAcHd+lJcOQPgM3/qLjJWJWliVRXQYBX+xGgV0/A24P0RY5qeJT0350K396WdHmK36zS702fpnD3ict/5BorpRzHpKllbZHsrL8rEKzWsC8FCN7zBS13RvK1j0JRYPHppRRRcfOfO14Kf2aQrq0QvQMbKQZr7FLcnveN2FzWgHtDG9qb24oT9JbSu/PQi5DKT0Z5FUK5bPul+ZiRrytBikGTYTYK4/9QDnjGeNmhZt1xvhUyWli01q93j7p2qMjoBh1cSF7s7r73FkiO29UGJ4xOp+fG2KdTIsJGwEfmKAoYDfslmDN+gjQ1Fq2B8XK+GZSWOU7RppFv4p+6JdEucX80Czlts+kqaQX+TSjjTQ7uFyZU9jYMnVv39yetTvFVRidYRFyD2HVcHmhT0SWj+AWcxyA8rU2dn0qrX8JLFOFS8QnUSprNA2iEwhHqbQa3eAFKikvijJPgaqSrD4JDlszF2F+emp48ggDrSyQH1RFPwhB9CfToj32A8I50P7YiPgf0/BBAq67TtW5phldNhhK/tLEoJ4XdtPGaICK5QnaOL70TCZmfBg7cudMC8WclCPYiuRPmXnxKvBmAVgk0zQGVcUEbt33hUtZda8i9VtjSBqzWXkv8ymtE="    
  file:
    '*.tar.xz'

  overwrite: true
  draft: false
  file_glob: true
  edge: true

  on:
    repo: kwrx/aplus-packages
    tags: false