
package: mpfr
version: 4.1.0
sources: 
  - https://gcc.gnu.org/pub/gcc/infrastructure/mpfr-$VERSION.tar.bz2

dependencies:
  - gmp

build:

  patches:
    - patches/mpfr-$VERSION.patch

  env:
    - DESTDIR: $SYSROOT
    - CFLAGS: -O2 -march=x86-64 -mtune=generic

  configure:
    - --prefix=/usr
    - --host=$HOST
    - --enable-static
    - --with-gmp=$PACKAGE_GMP/__out/usr
    - --with-sysroot=$SYSROOT

  make:
    - -j$(nproc)

  install:
    - -j$(nproc)