
package: isl
version: "0.24"
sources: 
  - https://gcc.gnu.org/pub/gcc/infrastructure/isl-$VERSION.tar.bz2

dependencies:
  - gmp

build:

  patches:
    - patches/isl-$VERSION.patch

  env:
    - DESTDIR: $SYSROOT
    - CFLAGS: -O2 -march=x86-64 -mtune=generic

  configure:
    - --prefix=/usr
    - --host=$HOST
    - --enable-static
    - --with-gmp=system
    - --with-gmp-prefix=$PACKAGE_GMP/__out/usr
    - --with-sysroot=$SYSROOT

  make:
    - -j$(nproc)

  install:
    - -j$(nproc)