
package: gmp
version: 6.2.1
sources: 
  - https://gcc.gnu.org/pub/gcc/infrastructure/gmp-$VERSION.tar.bz2

build:

  patches:
    - patches/gmp-$VERSION.patch

  env:
    - DESTDIR: $SYSROOT
    - CFLAGS: -O2 -march=x86-64 -mtune=generic

  configure:
    - --prefix=/usr
    - --host=$HOST
    - --enable-static
    - --with-sysroot=$SYSROOT

  make:
    - -j$(nproc)

  install:
    - -j$(nproc)