
package: binutils
version: "2.38"
sources: 
  - https://ftp.gnu.org/gnu/binutils/binutils-$VERSION.tar.xz

build:

  patches:
    - patches/binutils-$VERSION.patch

  env:
   - DESTDIR: $SYSROOT
   - CFLAGS: -O2 -march=x86-64 -mtune=generic

  configure:
    - --prefix=/usr
    - --host=$HOST
    - --enable-static
    - --enable-lto
    - --disable-shared
    - --disable-host-shared
    - --disable-werror
    - --with-sysroot=$SYSROOT

  make:
    - -j$(nproc)

  install:
    - -j$(nproc)