
package: libpng
version: 1.6.37
sources: 
  - https://download.sourceforge.net/libpng/libpng-$VERSION.tar.xz

dependencies:
  - zlib

build:

  patches:
   - patches/libpng-$VERSION.patch

  env:
   - DESTDIR: $SYSROOT
   - CFLAGS: -O2 -march=x86-64 -mtune=generic -I$PACKAGE_ZLIB/__out/usr/include
   - CPPFLAGS: -O2 -march=x86-64 -mtune=generic -I$PACKAGE_ZLIB/__out/usr/include
   - LDFLAGS: -L$PACKAGE_ZLIB/__out/usr/lib
   - LIBS: -lz

  configure:
    - --prefix=/usr
    - --host=$HOST
    - --enable-static
    - --enable-shared=no
    - --with-sysroot=$SYSROOT

  make:
    - -j$(nproc)

  install:
    - -j$(nproc)