
package: libpng
version: 1.6.37
sources: 
  - https://download.sourceforge.net/libpng/libpng-$VERSION.tar.xz

dependencies:
  - zlib

build:

  patches:
    - patches/libpng-$VERSION.patch

  env:
    - DESTDIR: $SYSROOT
    - CFLAGS: -O2 -march=x86-64 -mtune=generic
    - CPPFLAGS: -I$PACKAGE_ZLIB/__out/usr/include
    - LDFLAGS: -L$PACKAGE_ZLIB/__out/usr/lib

  configure:
    - --prefix=/usr
    - --host=$HOST
    - --enable-static
    - --enable-shared=no
    - --enable-intel-sse
    - --with-sysroot=$SYSROOT

  make:
    - -j$(nproc)

  install:
    - -j$(nproc)