
package: freetype
version: 2.12.1
sources: 
  - https://download.savannah.gnu.org/releases/freetype/freetype-$VERSION.tar.xz

dependencies:
  - libpng
  - zlib

build:

  patches:
    - patches/freetype-$VERSION.patch

  env:
    - DESTDIR: $SYSROOT
    - ZLIB_CFLAGS: -I$PACKAGE_ZLIB/__out/usr/include
    - ZLIB_LIBS: -lz
    - LIBPNG_CFLAGS: -I$PACKAGE_LIBPNG/__out/usr/include
    - LIBPNG_LIBS: -lpng -lz
    - CFLAGS: -O2 -march=x86-64 -mtune=generic -I$PACKAGE_ZLIB/__out/usr/include -I$PACKAGE_LIBPNG/__out/usr/include

  configure:
    - --prefix=/usr
    - --host=$HOST
    - --enable-static
    - --disable-shared
    - --disable-mmap
    - --disable-freetype-config
    - --without-pthreads
    - --without-harfbuzz
    - --without-bzip2
    - --without-brotli
    - --without-librsvg
    - --with-zlib
    - --with-png
    - --with-sysroot=$SYSROOT

  make:
    - -j$(nproc)

  install:
    - -j$(nproc)