set(CMAKE_SYSTEM_NAME aplus)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER x86_64-aplus-gcc)
set(CMAKE_CXX_COMPILER x86_64-aplus-g++)

set(CMAKE_C_FLAGS "-fno-PIE -static" CACHE STRING "" FORCE)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)