name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Prepare environment
      working-directory: ${{github.workspace}}
      shell: bash
      run: sudo apt update && sudo apt install -y wget bison flex build-essential python3 python3-pip unzip

    - name: Prepare build-system
      working-directory: ${{github.workspace}}
      shell: bash
      run: ci/prepare-and-build.sh
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ${{github.workspace}}/*.tar.xz
