name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Prepare environment
      working-directory: ${{github.workspace}}
      shell: bash
      run: sudo apt update && sudo apt install bison flex build-essential python3 python3-pip && pip install -r ${{github.workspace}}/requirements.txt

    - name: Build generic packages
      working-directory: ${{github.workspace}}
      shell: bash
      run: ci/build.sh

    - name: Build packages
      working-directory: ${{github.workspace}}
      shell: bash
      run: python3 ci/build.py --clean
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ${{github.workspace}}/*.tar.xz
